name: "transformer_comm"
backend: "python"
max_batch_size: 0
default_model_filename: "model.py"
input [
  {
    name: "input_data"
    data_type: TYPE_FP32
    dims: [ 30, 3 ]
  }
]
output [
  {
    name: "predictions"
    data_type: TYPE_FP32
    dims: [ 10, 3 ]
  },
  {
    name: "anomaly_score"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
